name: Build and deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
env:
  AZURE_WEBAPP_NAME: 'atc-demo'
  APP_OUTPUT_PATH: './src/Server/app/atc-demo'
  DOTNET_VERSION: '6.0.x'
# TODO:   AZURE_WEBAPP_PUBLISH_PROFILE

defaults:
  run:
    working-directory: 'src'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.      

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      # TODO: Remove once fixed: https://github.com/dotnet/format/issues/1519
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format --version "6.*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Run NBGV
        id: version
        uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - name: Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: Run dotnet format
        id: format
        # TODO: Rename to dotnet format once #1519 fixed
        run: dotnet-format --verbosity diagnostic --verify-no-changes

      - name: Run dotnet test
        id: test
        run: dotnet test --configuration Release
      
      - name: Run dotnet publish
        id: publish
        run: |
          cd ./Server
          dotnet publish --configuration Release --output ${{ env.APP_OUTPUT_PATH }}
     
      # TODO: Deploy to Azure Web apps
      #- name: 'Run Azure webapp deploy action using publish profile credentials'
      #  id: deploy
      #  uses: azure/webapps-deploy@v2
      #  with: 
      #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
      #    package: '${{ env.APP_OUTPUT_PATH }}'
